"""Render the Quarterly Outlook report from collected tool-call records.

Mirrors ``report_generators.py``'s discipline for the initiation of coverage:
every figure in the rendered report is read back out of what Claude actually
recorded (or, for Section I, out of the fetched macro evidence). Nothing here
invents, averages, or silently pads a missing record -- a section without the
backing data says so explicitly instead of being fabricated or omitted
without comment.

Two small, explicitly-documented rendering conventions turn recorded facts
into reader-facing labels without inventing new figures:

1. ``TILT_DISPLAY_LABELS`` maps a recorded ``overweight``/``neutral``/
   ``underweight`` call onto a standardized "+2%/0%/-2%" display string. This
   is a presentation convention standing in for a real portfolio-optimizer
   weight, not a derived or asserted number -- documented at its point of use
   in ``outlook_report.py`` as well.
2. ``SCENARIO_BETA_LABELS`` / ``SCENARIO_TILT_LABELS`` (Section VIII) map a
   scenario's name onto a qualitative beta/positioning descriptor. These are
   fixed narrative labels for a positioning summary table, not new
   quantitative claims.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence

from render_helpers import format_number, markdown_table

#: Canonical ordering for the three cases wherever they are listed together.
SCENARIO_ORDER: Dict[str, int] = {"bull": 0, "base": 1, "bear": 2}

#: Display convention (see module docstring) applied by ``outlook_report.py``
#: when it derives the top-level ``sector_tilts`` dict; re-exported here so
#: the render layer and the orchestration layer agree on one source of truth.
TILT_DISPLAY_LABELS: Dict[str, str] = {
    "overweight": "+2%",
    "neutral": "0%",
    "underweight": "-2%",
}

_SCENARIO_BETA_LABELS: Dict[str, str] = {
    "bull": "High beta / pro-cyclical",
    "base": "Market beta (~1.0x)",
    "bear": "Low beta / defensive",
}

_SCENARIO_TILT_LABELS: Dict[str, str] = {
    "bull": "Risk-on",
    "base": "Balanced",
    "bear": "Risk-off",
}


@dataclass
class MacroScenarioRecord:
    """One ``record_macro_scenario`` tool call."""

    name: str
    probability_weight: float
    gdp_growth_pct: float
    inflation_pct: float
    fed_funds_rate_pct: float
    ten_year_yield_pct: float
    eps_growth_pct: float
    trigger_or_narrative: str
    winners: List[str] = field(default_factory=list)
    losers: List[str] = field(default_factory=list)


@dataclass
class SectorTiltRecord:
    """One ``record_sector_tilt`` tool call."""

    sector: str
    scenario: str
    earnings_growth_pct: float
    pe_ratio: float
    tilt: str
    rationale: str


@dataclass
class RelativeValueRecord:
    """One ``record_relative_value_view`` tool call."""

    pair_name: str
    metric_a_label: str
    metric_a_value: str
    metric_b_label: str
    metric_b_value: str
    verdict: str
    rationale: str


@dataclass
class CatalystRecord:
    """One ``record_catalyst`` tool call."""

    name: str
    date: str
    impact: str


@dataclass
class TailRiskRecord:
    """One ``flag_tail_risk`` tool call."""

    description: str
    category: str


def _scenario_by_name(scenarios: Sequence[MacroScenarioRecord]) -> Dict[str, MacroScenarioRecord]:
    return {record.name: record for record in scenarios}


def _ordered_scenario_names(scenarios: Sequence[MacroScenarioRecord]) -> List[str]:
    names = {record.name for record in scenarios}
    return sorted(names, key=lambda name: SCENARIO_ORDER.get(name.lower(), 99))


def _cover(quarter: str, macro_scenario_requested: str, status: str) -> str:
    return (
        f"# Quarterly Outlook: {quarter}\n\n"
        f"> Headline scenario requested by the caller: **{macro_scenario_requested.title()}**. "
        "All three cases (Bull/Base/Bear) are constructed and recorded in full regardless of "
        "which one is headlined below.\n>\n"
        "> Generated by the analyst-agent quarterly-outlook orchestrator from deterministic "
        "mock macro evidence (`outlook_evidence.fetch_macro_evidence`). Figures are internally "
        f"consistent synthetic data, not live market data, and must not inform an investment "
        f"decision. Run status: **{status}**.\n"
    )


def _executive_summary(scenarios: Sequence[MacroScenarioRecord]) -> str:
    lines = ["## Executive Summary\n"]
    if not scenarios:
        lines.append("_No macro scenarios were recorded; no executive summary can be rendered._\n")
        return "\n".join(lines)
    by_name = _scenario_by_name(scenarios)
    for name in _ordered_scenario_names(scenarios):
        record = by_name[name]
        probability_pct = format_number(record.probability_weight * 100, 0)
        headline = record.trigger_or_narrative.strip().split(". ")[0].rstrip(".")
        lines.append(f"- **{name}** ({probability_pct}% probability): {headline}.")
    lines.append("")
    return "\n".join(lines)


def _section_i_macro_backdrop(evidence: Dict[str, Any]) -> str:
    lines = ["## I. Macro Scenario\n"]
    history = evidence.get("macro_history", []) or []
    forward = evidence.get("macro_forward_estimate", {}) or {}
    indicators = evidence.get("economic_indicators", {}) or {}
    rates_fx = evidence.get("rates_fx", {}) or {}

    if not history and not forward:
        lines.append("_No macro evidence was supplied for this run._\n")
        return "\n".join(lines)

    lines.append(
        "Growth, inflation, and rates evidence for the trailing quarters and the requested "
        "quarter, as fetched by `outlook_evidence.fetch_macro_evidence` (deterministic mock "
        "data standing in for a live macro data provider):\n"
    )
    rows = [
        [
            point.get("quarter", ""),
            f"{format_number(point.get('gdp_growth_yoy_pct'))}%",
            f"{format_number(point.get('cpi_headline_pct'))}%",
            f"{format_number(point.get('fed_funds_rate_pct'))}%",
            f"{format_number(point.get('ten_year_yield_pct'))}%",
            f"{format_number(point.get('sp500_eps_growth_yoy_pct'))}%",
        ]
        for point in history
    ]
    current = forward.get("current_quarter")
    if isinstance(current, dict):
        rows.append(
            [
                f"{current.get('quarter', '')} (current)",
                f"{format_number(current.get('gdp_growth_yoy_pct'))}%",
                f"{format_number(current.get('cpi_headline_pct'))}%",
                f"{format_number(current.get('fed_funds_rate_pct'))}%",
                f"{format_number(current.get('ten_year_yield_pct'))}%",
                f"{format_number(current.get('sp500_eps_growth_yoy_pct'))}%",
            ]
        )
    next_q = forward.get("next_quarter_forecast")
    if isinstance(next_q, dict):
        rows.append(
            [
                f"{next_q.get('quarter', '')} (forecast)",
                f"{format_number(next_q.get('gdp_growth_yoy_pct'))}%",
                f"{format_number(next_q.get('cpi_headline_pct'))}%",
                f"{format_number(next_q.get('fed_funds_rate_pct'))}%",
                f"{format_number(next_q.get('ten_year_yield_pct'))}%",
                f"{format_number(next_q.get('sp500_eps_growth_yoy_pct'))}%",
            ]
        )
    lines.append(
        markdown_table(
            ["Quarter", "GDP YoY", "CPI (headline)", "Fed funds", "10Y yield", "S&P 500 EPS YoY"],
            rows,
        )
    )
    lines.append("")
    if forward.get("fed_policy_guidance"):
        lines.append(f"**Fed guidance:** {forward['fed_policy_guidance']}.\n")

    if indicators:
        lines.append(
            "**Economic indicators:** "
            f"manufacturing PMI {format_number(indicators.get('pmi_manufacturing'))}, "
            f"services PMI {format_number(indicators.get('pmi_services'))}, "
            f"consumer confidence {format_number(indicators.get('consumer_confidence_index'))}, "
            f"S&P 500 earnings revisions trend **{indicators.get('sp500_earnings_revisions_trend', 'n/a')}**, "
            f"equity risk premium {format_number(indicators.get('equity_risk_premium_pct'))}% "
            f"(S&P 500 forward P/E {format_number(indicators.get('sp500_forward_pe'))}x earnings "
            f"yield less the 10-year yield).\n"
        )
    if rates_fx:
        futures_path = rates_fx.get("fed_funds_futures_implied_path", []) or []
        path_text = ", ".join(
            f"{step.get('quarter')}: {format_number(step.get('implied_fed_funds_rate_pct'))}%"
            for step in futures_path
        )
        lines.append(
            "**Rates and FX:** Fed funds futures imply "
            f"{path_text or 'no forward path recorded'}; 2s10s spread "
            f"{format_number(rates_fx.get('two_year_ten_year_spread_bps'))} bps; USD index "
            f"{format_number(rates_fx.get('usd_index'))}.\n"
        )
    return "\n".join(lines)


def _sector_table(tilts: Sequence[SectorTiltRecord]) -> str:
    return markdown_table(
        ["Sector", "Earnings growth", "Forward P/E", "Recommendation"],
        [
            [
                record.sector,
                f"{format_number(record.earnings_growth_pct)}%",
                f"{format_number(record.pe_ratio)}x",
                record.tilt,
            ]
            for record in tilts
        ],
    )


def _section_ii_base_case(
    scenarios: Sequence[MacroScenarioRecord],
    sector_tilts: Sequence[SectorTiltRecord],
    sector_universe: Sequence[str],
) -> str:
    lines = ["## II. Base Case\n"]
    by_name = _scenario_by_name(scenarios)
    base = by_name.get("Base")
    if base is None:
        lines.append("_No Base scenario was recorded. This is the load-bearing case for the "
                      "report and its absence is a material gap -- see notes._\n")
    else:
        lines.append(
            f"Probability weight **{format_number(base.probability_weight * 100, 0)}%**. "
            f"{base.trigger_or_narrative}\n"
        )
        lines.append(
            markdown_table(
                ["Metric", "Base case"],
                [
                    ["GDP growth (YoY)", f"{format_number(base.gdp_growth_pct)}%"],
                    ["Inflation (YoY)", f"{format_number(base.inflation_pct)}%"],
                    ["Fed funds rate", f"{format_number(base.fed_funds_rate_pct)}%"],
                    ["10-year yield", f"{format_number(base.ten_year_yield_pct)}%"],
                    ["S&P 500 EPS growth", f"{format_number(base.eps_growth_pct)}%"],
                ],
            )
        )
        lines.append("")

    base_tilts = [record for record in sector_tilts if record.scenario == "Base"]
    lines.append("### Sector implications (Base case)\n")
    if base_tilts:
        lines.append(_sector_table(base_tilts))
        lines.append("")
        covered = {record.sector for record in base_tilts}
        missing = [sector for sector in sector_universe if sector not in covered]
        if missing:
            lines.append(
                f"> **Coverage gap:** {len(missing)} of {len(sector_universe)} sectors in the "
                f"requested universe have no recorded Base-case tilt and are omitted from the "
                f"table above rather than padded with an invented row: {', '.join(missing)}.\n"
            )
    else:
        lines.append("_No sector tilts were recorded for the Base case._\n")

    if base is not None and (base.winners or base.losers):
        lines.append("### Portfolio positioning summary\n")
        if base.winners:
            lines.append(f"- **Overweight lean:** {', '.join(base.winners)}.")
        if base.losers:
            lines.append(f"- **Underweight lean:** {', '.join(base.losers)}.")
        lines.append("")
    return "\n".join(lines)


def _directional_case_section(
    heading: str,
    case_name: str,
    scenarios: Sequence[MacroScenarioRecord],
    sector_tilts: Sequence[SectorTiltRecord],
) -> str:
    lines = [f"## {heading}\n"]
    by_name = _scenario_by_name(scenarios)
    record = by_name.get(case_name)
    base = by_name.get("Base")
    if record is None:
        lines.append(f"_No {case_name} scenario was recorded -- see notes._\n")
        return "\n".join(lines)

    lines.append(
        f"Probability weight **{format_number(record.probability_weight * 100, 0)}%**.\n"
    )
    lines.append(f"**Trigger and narrative:** {record.trigger_or_narrative}\n")

    lines.append("**What would need to be true:**\n")
    lines.append(f"- GDP growth of {format_number(record.gdp_growth_pct)}% year over year"
                  + (f" (vs. {format_number(base.gdp_growth_pct)}% in the Base case)" if base else "")
                  + ".")
    lines.append(f"- Inflation of {format_number(record.inflation_pct)}%"
                  + (f" (vs. {format_number(base.inflation_pct)}% Base)" if base else "")
                  + ".")
    lines.append(f"- Fed funds rate at {format_number(record.fed_funds_rate_pct)}%"
                  + (f" (vs. {format_number(base.fed_funds_rate_pct)}% Base)" if base else "")
                  + ".")
    lines.append(f"- S&P 500 EPS growth of {format_number(record.eps_growth_pct)}%"
                  + (f" (vs. {format_number(base.eps_growth_pct)}% Base)" if base else "")
                  + ".")
    lines.append("")

    if record.winners:
        lines.append(f"**Winners:** {', '.join(record.winners)}.\n")
    if record.losers:
        lines.append(f"**Losers:** {', '.join(record.losers)}.\n")

    case_tilts = [t for t in sector_tilts if t.scenario == case_name]
    if case_tilts:
        lines.append(f"### Sector calls under the {case_name} case\n")
        lines.append(_sector_table(case_tilts))
        lines.append("")
    return "\n".join(lines)


def _section_v_relative_value(views: Sequence[RelativeValueRecord]) -> str:
    lines = ["## V. Relative Value Views\n"]
    if not views:
        lines.append("_No relative-value views were recorded._\n")
        return "\n".join(lines)
    for view in views:
        lines.append(f"### {view.pair_name}\n")
        lines.append(
            markdown_table(
                ["Metric", "Value"],
                [
                    [view.metric_a_label, view.metric_a_value],
                    [view.metric_b_label, view.metric_b_value],
                ],
            )
        )
        lines.append(f"\n**Verdict:** {view.verdict} _{view.rationale}_\n")
    if len(views) < 3:
        lines.append(
            f"> Only {len(views)} relative-value view(s) were recorded; the report expects at "
            "least three (Growth vs Value, Quality Premium, Bonds vs Equities).\n"
        )
    return "\n".join(lines)


def _section_vi_catalyst_calendar(catalysts: Sequence[CatalystRecord]) -> str:
    lines = ["## VI. Sector Catalyst Calendar\n"]
    if not catalysts:
        lines.append("_No catalysts were recorded._\n")
        return "\n".join(lines)
    ordered = sorted(catalysts, key=lambda record: record.date)
    lines.append(
        markdown_table(
            ["Date", "Catalyst", "Impact"],
            [[record.date, record.name, record.impact] for record in ordered],
        )
    )
    lines.append("")
    if len(catalysts) < 3:
        lines.append(
            f"> Only {len(catalysts)} catalyst(s) were recorded; the report expects at least three.\n"
        )
    return "\n".join(lines)


def _section_vii_key_risks(
    tail_risks: Sequence[TailRiskRecord], scenarios: Sequence[MacroScenarioRecord]
) -> str:
    lines = ["## VII. Key Risks to Base Case\n", "### Downside risks\n"]
    if tail_risks:
        for risk in tail_risks:
            lines.append(f"- **[{risk.category}]** {risk.description}")
        if len(tail_risks) < 2:
            lines.append(
                f"\n> Only {len(tail_risks)} downside risk(s) were recorded; the report expects "
                "at least two.\n"
            )
    else:
        lines.append("_No tail risks were recorded._")
    lines.append("")

    lines.append("### Upside risks\n")
    by_name = _scenario_by_name(scenarios)
    bull = by_name.get("Bull")
    upside_items: List[str] = []
    if bull is not None:
        if bull.trigger_or_narrative:
            upside_items.append(bull.trigger_or_narrative)
        for sector in bull.winners:
            upside_items.append(f"{sector} re-rates or outperforms if the Bull case plays out.")
    if len(upside_items) >= 2:
        for item in upside_items:
            lines.append(f"- {item}")
    else:
        lines.append(
            "_Fewer than two upside risks can be derived from the recorded Bull case (missing "
            "narrative or winner sectors); not fabricated to hit a minimum._"
        )
    lines.append("")
    return "\n".join(lines)


def _section_viii_positioning_summary(
    scenarios: Sequence[MacroScenarioRecord], sector_tilts: Sequence[SectorTiltRecord]
) -> str:
    lines = ["## VIII. Positioning Summary\n"]
    if not scenarios:
        lines.append("_No scenarios were recorded; no positioning summary can be rendered._\n")
        return "\n".join(lines)
    by_name = _scenario_by_name(scenarios)
    rows = []
    for name in _ordered_scenario_names(scenarios):
        record = by_name[name]
        key = name.lower()
        rows.append(
            [
                name,
                f"{format_number(record.probability_weight * 100, 0)}%",
                _SCENARIO_TILT_LABELS.get(key, "n/a"),
                _SCENARIO_BETA_LABELS.get(key, "n/a"),
                ", ".join(record.winners) if record.winners else "n/a",
            ]
        )
    lines.append(markdown_table(["Scenario", "Probability", "Tilt", "Beta", "Key bets"], rows))
    lines.append(
        "\n> Tilt and Beta are fixed qualitative labels for this summary table (Bull = "
        "risk-on/high beta, Base = balanced/market beta, Bear = risk-off/defensive), not "
        "additional recorded figures.\n"
    )
    return "\n".join(lines)


def _notes_section(notes: Sequence[str], status: str) -> str:
    lines = ["## Notes\n"]
    lines.append(
        "This outlook is rendered entirely from tool calls collected in one Claude "
        "conversation against deterministic mock macro evidence. It is not built from a "
        "persistent workspace and nothing here is written to disk by this report type "
        "itself.\n"
    )
    if notes:
        lines.append(f"**Run status: {status}.** Coverage shortfalls detected in this run:\n")
        for note in notes:
            lines.append(f"- {note}")
    else:
        lines.append(f"**Run status: {status}.** No coverage shortfalls were detected.")
    return "\n".join(lines) + "\n"


def render_outlook_markdown(
    quarter: str,
    macro_scenario_requested: str,
    macro_scenarios: Sequence[MacroScenarioRecord],
    sector_tilts: Sequence[SectorTiltRecord],
    relative_value_views: Sequence[RelativeValueRecord],
    catalysts: Sequence[CatalystRecord],
    tail_risks: Sequence[TailRiskRecord],
    sector_universe: Sequence[str],
    evidence: Dict[str, Any],
    notes: Sequence[str],
    status: str,
) -> str:
    """Render the eight-section Quarterly Outlook as Markdown.

    Every section is built only from the records actually passed in; a
    section with nothing to render says so explicitly (mirroring
    ``report_generators.initiation_report_markdown``) instead of being
    silently dropped or padded with invented rows.

    Args:
        quarter: Quarter label, e.g. ``"Q1 2025"``.
        macro_scenario_requested: The case the caller wanted headlined.
        macro_scenarios: Collected ``record_macro_scenario`` calls.
        sector_tilts: Collected ``record_sector_tilt`` calls.
        relative_value_views: Collected ``record_relative_value_view`` calls.
        catalysts: Collected ``record_catalyst`` calls.
        tail_risks: Collected ``flag_tail_risk`` calls.
        sector_universe: The full requested sector list, used only to report
            coverage gaps -- never to fabricate a missing row.
        evidence: The payload from ``outlook_evidence.fetch_macro_evidence``,
            used for Section I's evidence-sourced macro backdrop.
        notes: Coverage-shortfall notes from ``outlook_report.py``.
        status: ``"success"``, ``"partial"``, or ``"failed"``.

    Returns:
        A Markdown document with a cover, an executive summary, and sections
        I through VIII.
    """

    sections = [
        _cover(quarter, macro_scenario_requested, status),
        _executive_summary(macro_scenarios),
        _section_i_macro_backdrop(evidence),
        _section_ii_base_case(macro_scenarios, sector_tilts, sector_universe),
        _directional_case_section("III. Bull Case", "Bull", macro_scenarios, sector_tilts),
        _directional_case_section("IV. Bear Case", "Bear", macro_scenarios, sector_tilts),
        _section_v_relative_value(relative_value_views),
        _section_vi_catalyst_calendar(catalysts),
        _section_vii_key_risks(tail_risks, macro_scenarios),
        _section_viii_positioning_summary(macro_scenarios, sector_tilts),
        _notes_section(notes, status),
    ]
    return "\n---\n\n".join(section.rstrip() + "\n" for section in sections)
